import type { SyntheticPolicyRecord } from './types';

export const syntheticPolicyRecords: SyntheticPolicyRecord[] = [
  {
    customer: {
      customerId: 'CUST-1001',
      policyholderName: 'Alicia Morgan',
      age: 34,
      gender: 'Female',
      postcode: 'SW1A 1AA',
      tenureYears: 8,
      employmentStatus: 'Employed',
      maritalStatus: 'Married',
      yearsAsPolicyholder: 6,
    },
    policy: {
      policyId: 'POL-2001',
      policyStatus: 'Active',
      effectiveDate: '2025-01-15',
      expiryDate: '2026-01-15',
      coverageType: 'Comprehensive',
      vehicleUse: 'Commute',
      annualMileage: 9200,
      priorInsuranceYears: 12,
      renewalCount: 4,
    },
    vehicle: {
      vehicleId: 'VEH-3001',
      make: 'Toyota',
      model: 'Corolla',
      year: 2022,
      fuelType: 'Hybrid',
      transmission: 'Automatic',
      engineSizeCc: 1800,
      vehicleValue: 26000,
      garagingPostcode: 'SW1A 1AA',
      isModified: false,
    },
    claimsHistory: {
      claimsInLast3Years: 0,
      atFaultClaims: 0,
      totalClaimAmount: 0,
      lastClaimMonthsAgo: null,
      claimSeverity: 'None',
      nearMissCount: 1,
    },
    telematics: {
      telematicsEnabled: true,
      averageSpeedKph: 48,
      harshBrakingEventsPer1000Km: 2.1,
      nightDrivingRatio: 0.18,
      phoneDistractionScore: 14,
      monthlyDistanceKm: 760,
    },
    premium: {
      currentPremiumAnnual: 1280,
      basePremiumAnnual: 1450,
      discountsApplied: 170,
      excessAmount: 400,
      paymentFrequency: 'Monthly',
      renewalNoticeDays: 30,
    },
    economicIndicators: {
      inflationIndex: 1.06,
      fuelPriceIndex: 1.08,
      repairCostIndex: 1.12,
      regionalRiskIndex: 0.74,
      claimsTrendIndex: 0.81,
    },
    riskBand: 'Low',
    notes: 'Low-risk commuter profile with strong telematics behaviour.',
  },
  {
    customer: {
      customerId: 'CUST-1002',
      policyholderName: 'Daniel Brooks',
      age: 41,
      gender: 'Male',
      postcode: 'M1 2AB',
      tenureYears: 5,
      employmentStatus: 'Employed',
      maritalStatus: 'Married',
      yearsAsPolicyholder: 4,
    },
    policy: {
      policyId: 'POL-2002',
      policyStatus: 'Active',
      effectiveDate: '2025-02-03',
      expiryDate: '2026-02-03',
      coverageType: 'Comprehensive',
      vehicleUse: 'Private',
      annualMileage: 12500,
      priorInsuranceYears: 9,
      renewalCount: 3,
    },
    vehicle: {
      vehicleId: 'VEH-3002',
      make: 'Ford',
      model: 'Focus',
      year: 2019,
      fuelType: 'Petrol',
      transmission: 'Manual',
      engineSizeCc: 1600,
      vehicleValue: 13500,
      garagingPostcode: 'M1 2AB',
      isModified: false,
    },
    claimsHistory: {
      claimsInLast3Years: 1,
      atFaultClaims: 1,
      totalClaimAmount: 2400,
      lastClaimMonthsAgo: 18,
      claimSeverity: 'Minor',
      nearMissCount: 2,
    },
    telematics: {
      telematicsEnabled: false,
      averageSpeedKph: 56,
      harshBrakingEventsPer1000Km: 4.3,
      nightDrivingRatio: 0.27,
      phoneDistractionScore: 31,
      monthlyDistanceKm: 1030,
    },
    premium: {
      currentPremiumAnnual: 1540,
      basePremiumAnnual: 1620,
      discountsApplied: 80,
      excessAmount: 500,
      paymentFrequency: 'Monthly',
      renewalNoticeDays: 21,
    },
    economicIndicators: {
      inflationIndex: 1.09,
      fuelPriceIndex: 1.11,
      repairCostIndex: 1.16,
      regionalRiskIndex: 0.89,
      claimsTrendIndex: 0.95,
    },
    riskBand: 'Moderate',
    notes: 'Moderate risk exposure due to higher mileage and one prior at-fault claim.',
  },
  {
    customer: {
      customerId: 'CUST-1003',
      policyholderName: 'Priya Shah',
      age: 29,
      gender: 'Female',
      postcode: 'B1 1AA',
      tenureYears: 3,
      employmentStatus: 'Employed',
      maritalStatus: 'Single',
      yearsAsPolicyholder: 2,
    },
    policy: {
      policyId: 'POL-2003',
      policyStatus: 'Active',
      effectiveDate: '2025-03-02',
      expiryDate: '2026-03-02',
      coverageType: 'ThirdPartyFireTheft',
      vehicleUse: 'Private',
      annualMileage: 7800,
      priorInsuranceYears: 5,
      renewalCount: 2,
    },
    vehicle: {
      vehicleId: 'VEH-3003',
      make: 'Volkswagen',
      model: 'Golf',
      year: 2021,
      fuelType: 'Petrol',
      transmission: 'Manual',
      engineSizeCc: 2000,
      vehicleValue: 19000,
      garagingPostcode: 'B1 1AA',
      isModified: false,
    },
    claimsHistory: {
      claimsInLast3Years: 0,
      atFaultClaims: 0,
      totalClaimAmount: 0,
      lastClaimMonthsAgo: null,
      claimSeverity: 'None',
      nearMissCount: 0,
    },
    telematics: {
      telematicsEnabled: true,
      averageSpeedKph: 45,
      harshBrakingEventsPer1000Km: 1.6,
      nightDrivingRatio: 0.15,
      phoneDistractionScore: 8,
      monthlyDistanceKm: 650,
    },
    premium: {
      currentPremiumAnnual: 1160,
      basePremiumAnnual: 1260,
      discountsApplied: 100,
      excessAmount: 450,
      paymentFrequency: 'Annually',
      renewalNoticeDays: 45,
    },
    economicIndicators: {
      inflationIndex: 1.05,
      fuelPriceIndex: 1.07,
      repairCostIndex: 1.1,
      regionalRiskIndex: 0.68,
      claimsTrendIndex: 0.79,
    },
    riskBand: 'Low',
    notes: 'Young driver profile with excellent telematics indicators.',
  },
  {
    customer: {
      customerId: 'CUST-1004',
      policyholderName: 'Marcus Lee',
      age: 48,
      gender: 'Male',
      postcode: 'EH1 2BC',
      tenureYears: 11,
      employmentStatus: 'Self-employed',
      maritalStatus: 'Married',
      yearsAsPolicyholder: 9,
    },
    policy: {
      policyId: 'POL-2004',
      policyStatus: 'Renewal',
      effectiveDate: '2024-11-10',
      expiryDate: '2025-11-10',
      coverageType: 'Comprehensive',
      vehicleUse: 'Business',
      annualMileage: 18000,
      priorInsuranceYears: 15,
      renewalCount: 6,
    },
    vehicle: {
      vehicleId: 'VEH-3004',
      make: 'BMW',
      model: '3 Series',
      year: 2020,
      fuelType: 'Diesel',
      transmission: 'Automatic',
      engineSizeCc: 2000,
      vehicleValue: 28000,
      garagingPostcode: 'EH1 2BC',
      isModified: false,
    },
    claimsHistory: {
      claimsInLast3Years: 2,
      atFaultClaims: 1,
      totalClaimAmount: 6400,
      lastClaimMonthsAgo: 12,
      claimSeverity: 'Moderate',
      nearMissCount: 3,
    },
    telematics: {
      telematicsEnabled: true,
      averageSpeedKph: 58,
      harshBrakingEventsPer1000Km: 5.7,
      nightDrivingRatio: 0.31,
      phoneDistractionScore: 26,
      monthlyDistanceKm: 1500,
    },
    premium: {
      currentPremiumAnnual: 2090,
      basePremiumAnnual: 2220,
      discountsApplied: 130,
      excessAmount: 600,
      paymentFrequency: 'Monthly',
      renewalNoticeDays: 24,
    },
    economicIndicators: {
      inflationIndex: 1.08,
      fuelPriceIndex: 1.1,
      repairCostIndex: 1.19,
      regionalRiskIndex: 0.93,
      claimsTrendIndex: 1.02,
    },
    riskBand: 'Moderate',
    notes: 'Higher business-use mileage and moderate claims pattern elevate exposure.',
  },
  {
    customer: {
      customerId: 'CUST-1005',
      policyholderName: 'Sofia Patel',
      age: 52,
      gender: 'Female',
      postcode: 'LS1 4AA',
      tenureYears: 7,
      employmentStatus: 'Retired',
      maritalStatus: 'Widowed',
      yearsAsPolicyholder: 5,
    },
    policy: {
      policyId: 'POL-2005',
      policyStatus: 'Active',
      effectiveDate: '2025-04-12',
      expiryDate: '2026-04-12',
      coverageType: 'Comprehensive',
      vehicleUse: 'Private',
      annualMileage: 6500,
      priorInsuranceYears: 20,
      renewalCount: 5,
    },
    vehicle: {
      vehicleId: 'VEH-3005',
      make: 'Audi',
      model: 'A4',
      year: 2017,
      fuelType: 'Diesel',
      transmission: 'Automatic',
      engineSizeCc: 2200,
      vehicleValue: 17500,
      garagingPostcode: 'LS1 4AA',
      isModified: false,
    },
    claimsHistory: {
      claimsInLast3Years: 1,
      atFaultClaims: 0,
      totalClaimAmount: 3100,
      lastClaimMonthsAgo: 26,
      claimSeverity: 'Minor',
      nearMissCount: 1,
    },
    telematics: {
      telematicsEnabled: true,
      averageSpeedKph: 41,
      harshBrakingEventsPer1000Km: 1.2,
      nightDrivingRatio: 0.09,
      phoneDistractionScore: 7,
      monthlyDistanceKm: 540,
    },
    premium: {
      currentPremiumAnnual: 1380,
      basePremiumAnnual: 1485,
      discountsApplied: 105,
      excessAmount: 350,
      paymentFrequency: 'Quarterly',
      renewalNoticeDays: 30,
    },
    economicIndicators: {
      inflationIndex: 1.07,
      fuelPriceIndex: 1.09,
      repairCostIndex: 1.13,
      regionalRiskIndex: 0.76,
      claimsTrendIndex: 0.87,
    },
    riskBand: 'Low',
    notes: 'Retired driver with stable annual mileage and low-risk telematics profile.',
  },
  {
    customer: {
      customerId: 'CUST-1006',
      policyholderName: 'Oliver Price',
      age: 36,
      gender: 'Male',
      postcode: 'G1 3QQ',
      tenureYears: 2,
      employmentStatus: 'Employed',
      maritalStatus: 'Single',
      yearsAsPolicyholder: 1,
    },
    policy: {
      policyId: 'POL-2006',
      policyStatus: 'Active',
      effectiveDate: '2025-05-21',
      expiryDate: '2026-05-21',
      coverageType: 'ThirdPartyOnly',
      vehicleUse: 'Commute',
      annualMileage: 15000,
      priorInsuranceYears: 6,
      renewalCount: 1,
    },
    vehicle: {
      vehicleId: 'VEH-3006',
      make: 'Peugeot',
      model: '208',
      year: 2023,
      fuelType: 'Petrol',
      transmission: 'Manual',
      engineSizeCc: 1400,
      vehicleValue: 14500,
      garagingPostcode: 'G1 3QQ',
      isModified: false,
    },
    claimsHistory: {
      claimsInLast3Years: 2,
      atFaultClaims: 1,
      totalClaimAmount: 4700,
      lastClaimMonthsAgo: 14,
      claimSeverity: 'Moderate',
      nearMissCount: 4,
    },
    telematics: {
      telematicsEnabled: false,
      averageSpeedKph: 62,
      harshBrakingEventsPer1000Km: 7.1,
      nightDrivingRatio: 0.34,
      phoneDistractionScore: 42,
      monthlyDistanceKm: 1250,
    },
    premium: {
      currentPremiumAnnual: 1715,
      basePremiumAnnual: 1790,
      discountsApplied: 75,
      excessAmount: 550,
      paymentFrequency: 'Monthly',
      renewalNoticeDays: 18,
    },
    economicIndicators: {
      inflationIndex: 1.11,
      fuelPriceIndex: 1.12,
      repairCostIndex: 1.18,
      regionalRiskIndex: 1.04,
      claimsTrendIndex: 1.08,
    },
    riskBand: 'High',
    notes: 'Higher-risk commute pattern with elevated distraction and harsh braking signals.',
  },
  {
    customer: {
      customerId: 'CUST-1007',
      policyholderName: 'Chloe Turner',
      age: 25,
      gender: 'Female',
      postcode: 'B90 3CD',
      tenureYears: 1,
      employmentStatus: 'Student',
      maritalStatus: 'Single',
      yearsAsPolicyholder: 1,
    },
    policy: {
      policyId: 'POL-2007',
      policyStatus: 'Active',
      effectiveDate: '2025-06-01',
      expiryDate: '2026-06-01',
      coverageType: 'Comprehensive',
      vehicleUse: 'Private',
      annualMileage: 9800,
      priorInsuranceYears: 3,
      renewalCount: 0,
    },
    vehicle: {
      vehicleId: 'VEH-3007',
      make: 'Kia',
      model: 'Rio',
      year: 2021,
      fuelType: 'Petrol',
      transmission: 'Manual',
      engineSizeCc: 1200,
      vehicleValue: 12000,
      garagingPostcode: 'B90 3CD',
      isModified: false,
    },
    claimsHistory: {
      claimsInLast3Years: 0,
      atFaultClaims: 0,
      totalClaimAmount: 0,
      lastClaimMonthsAgo: null,
      claimSeverity: 'None',
      nearMissCount: 1,
    },
    telematics: {
      telematicsEnabled: true,
      averageSpeedKph: 55,
      harshBrakingEventsPer1000Km: 6.4,
      nightDrivingRatio: 0.28,
      phoneDistractionScore: 38,
      monthlyDistanceKm: 820,
    },
    premium: {
      currentPremiumAnnual: 1625,
      basePremiumAnnual: 1750,
      discountsApplied: 125,
      excessAmount: 500,
      paymentFrequency: 'Monthly',
      renewalNoticeDays: 15,
    },
    economicIndicators: {
      inflationIndex: 1.1,
      fuelPriceIndex: 1.12,
      repairCostIndex: 1.14,
      regionalRiskIndex: 0.95,
      claimsTrendIndex: 0.99,
    },
    riskBand: 'Moderate',
    notes: 'Newer driver with moderate risk; telematics shows some speed and distraction patterns.',
  },
  {
    customer: {
      customerId: 'CUST-1008',
      policyholderName: 'Ethan Foster',
      age: 45,
      gender: 'Male',
      postcode: 'CR0 1FG',
      tenureYears: 13,
      employmentStatus: 'Employed',
      maritalStatus: 'Married',
      yearsAsPolicyholder: 10,
    },
    policy: {
      policyId: 'POL-2008',
      policyStatus: 'Active',
      effectiveDate: '2025-01-12',
      expiryDate: '2026-01-12',
      coverageType: 'Comprehensive',
      vehicleUse: 'Private',
      annualMileage: 11000,
      priorInsuranceYears: 18,
      renewalCount: 7,
    },
    vehicle: {
      vehicleId: 'VEH-3008',
      make: 'Mercedes',
      model: 'C-Class',
      year: 2020,
      fuelType: 'Diesel',
      transmission: 'Automatic',
      engineSizeCc: 2200,
      vehicleValue: 32000,
      garagingPostcode: 'CR0 1FG',
      isModified: false,
    },
    claimsHistory: {
      claimsInLast3Years: 0,
      atFaultClaims: 0,
      totalClaimAmount: 0,
      lastClaimMonthsAgo: null,
      claimSeverity: 'None',
      nearMissCount: 0,
    },
    telematics: {
      telematicsEnabled: true,
      averageSpeedKph: 46,
      harshBrakingEventsPer1000Km: 1.4,
      nightDrivingRatio: 0.11,
      phoneDistractionScore: 9,
      monthlyDistanceKm: 900,
    },
    premium: {
      currentPremiumAnnual: 1475,
      basePremiumAnnual: 1600,
      discountsApplied: 125,
      excessAmount: 450,
      paymentFrequency: 'Quarterly',
      renewalNoticeDays: 35,
    },
    economicIndicators: {
      inflationIndex: 1.06,
      fuelPriceIndex: 1.08,
      repairCostIndex: 1.12,
      regionalRiskIndex: 0.81,
      claimsTrendIndex: 0.84,
    },
    riskBand: 'Low',
    notes: 'Skillful, low-mileage driver with strong claims-free history.',
  },
  {
    customer: {
      customerId: 'CUST-1009',
      policyholderName: 'Imogen Wright',
      age: 38,
      gender: 'Female',
      postcode: 'N1 2DE',
      tenureYears: 6,
      employmentStatus: 'Employed',
      maritalStatus: 'Married',
      yearsAsPolicyholder: 4,
    },
    policy: {
      policyId: 'POL-2009',
      policyStatus: 'Active',
      effectiveDate: '2025-02-18',
      expiryDate: '2026-02-18',
      coverageType: 'Comprehensive',
      vehicleUse: 'Private',
      annualMileage: 13800,
      priorInsuranceYears: 10,
      renewalCount: 4,
    },
    vehicle: {
      vehicleId: 'VEH-3009',
      make: 'Honda',
      model: 'Civic',
      year: 2018,
      fuelType: 'Hybrid',
      transmission: 'Automatic',
      engineSizeCc: 1800,
      vehicleValue: 17000,
      garagingPostcode: 'N1 2DE',
      isModified: false,
    },
    claimsHistory: {
      claimsInLast3Years: 1,
      atFaultClaims: 0,
      totalClaimAmount: 1900,
      lastClaimMonthsAgo: 20,
      claimSeverity: 'Minor',
      nearMissCount: 2,
    },
    telematics: {
      telematicsEnabled: true,
      averageSpeedKph: 52,
      harshBrakingEventsPer1000Km: 3.1,
      nightDrivingRatio: 0.22,
      phoneDistractionScore: 18,
      monthlyDistanceKm: 1150,
    },
    premium: {
      currentPremiumAnnual: 1505,
      basePremiumAnnual: 1650,
      discountsApplied: 145,
      excessAmount: 475,
      paymentFrequency: 'Monthly',
      renewalNoticeDays: 22,
    },
    economicIndicators: {
      inflationIndex: 1.08,
      fuelPriceIndex: 1.09,
      repairCostIndex: 1.15,
      regionalRiskIndex: 0.84,
      claimsTrendIndex: 0.91,
    },
    riskBand: 'Moderate',
    notes: 'Stable insurance history; telematics remains within acceptable range.',
  },
  {
    customer: {
      customerId: 'CUST-1010',
      policyholderName: 'Noah Green',
      age: 55,
      gender: 'Male',
      postcode: 'M14 7GH',
      tenureYears: 9,
      employmentStatus: 'Employed',
      maritalStatus: 'Divorced',
      yearsAsPolicyholder: 8,
    },
    policy: {
      policyId: 'POL-2010',
      policyStatus: 'Lapsed',
      effectiveDate: '2024-06-10',
      expiryDate: '2025-06-10',
      coverageType: 'ThirdPartyFireTheft',
      vehicleUse: 'Private',
      annualMileage: 17500,
      priorInsuranceYears: 12,
      renewalCount: 5,
    },
    vehicle: {
      vehicleId: 'VEH-3010',
      make: 'Volvo',
      model: 'V40',
      year: 2016,
      fuelType: 'Diesel',
      transmission: 'Manual',
      engineSizeCc: 2000,
      vehicleValue: 11000,
      garagingPostcode: 'M14 7GH',
      isModified: false,
    },
    claimsHistory: {
      claimsInLast3Years: 3,
      atFaultClaims: 2,
      totalClaimAmount: 9800,
      lastClaimMonthsAgo: 9,
      claimSeverity: 'Severe',
      nearMissCount: 5,
    },
    telematics: {
      telematicsEnabled: false,
      averageSpeedKph: 64,
      harshBrakingEventsPer1000Km: 8.2,
      nightDrivingRatio: 0.39,
      phoneDistractionScore: 55,
      monthlyDistanceKm: 1450,
    },
    premium: {
      currentPremiumAnnual: 2360,
      basePremiumAnnual: 2490,
      discountsApplied: 130,
      excessAmount: 700,
      paymentFrequency: 'Annually',
      renewalNoticeDays: 12,
    },
    economicIndicators: {
      inflationIndex: 1.14,
      fuelPriceIndex: 1.13,
      repairCostIndex: 1.22,
      regionalRiskIndex: 1.18,
      claimsTrendIndex: 1.13,
    },
    riskBand: 'High',
    notes: 'High-risk profile with multiple claims, elevated speed, and higher repair costs.',
  },
];
